version: '3'

services:
  upload-server:
    build: .
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./config:/app/config
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
