# Passwords are stored as bcrypt hashes
# Default password: "admin" (change in production!)
users:
  - username: admin
    password_hash: "$2a$12$A/5mXeMmlI6VKJ8FuAufLObZWPF.ZJalEaTDaYTFo7P9d5ZTsftdi"
